language: node_js
node_js: node
cache: npm
env:
- TEST_ENV=cjs
- TEST_ENV=umd
- TEST_ENV=source
script:
- npm test
jobs:
  include:
  - stage: Release
    if: tag =~ ^v[0-9]
    env: NPM_TAG=$([[ "$TRAVIS_TAG" == *-* ]] && echo "next" || echo "latest")
    script: echo "Releasing $TRAVIS_TAG to npm with tag \"$NPM_TAG\" ..."
    before_deploy:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > "$HOME/.npmrc"
    deploy:
      provider: script
      skip_cleanup: true
      script: lerna publish from-git -y --dist-tag $NPM_TAG
      on:
        tags: true
  - stage: Deploy Website
    if: branch = website
    env: PUBLIC_PATH=/react-router/
    # The website is built as part of the deploy script,
    # so we don't need to build it yet.
    before_script: npm run build -- --no-website
    script: echo "Deploying website to https://reacttraining.com$PUBLIC_PATH"
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_70c5e56b421c_key -iv $encrypted_70c5e56b421c_iv
      -in website_deploy_key.enc -out website_deploy_key -d
    - chmod 600 website_deploy_key
    - eval $(ssh-agent -s)
    - ssh-add website_deploy_key
    deploy:
      provider: script
      script: bash scripts/deploy-website.sh
      skip_cleanup: true
      on:
        branch: website
